-- 04(조건에 맞는 도서와 저자 리스트 출력하기).sql
-- https://school.programmers.co.kr/learn/courses/30/lessons/144854
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS B INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID 
WHERE B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE;
