-- https://school.programmers.co.kr/learn/courses/30/lessons/157339
-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기.sql

SELECT T1.CAR_ID,
       T1.CAR_TYPE,
       FLOOR(T1.DAILY_FEE * (100 - T3.DISCOUNT_RATE) / 100) * 30 AS FEE
  FROM CAR_RENTAL_COMPANY_CAR AS T1
       JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS T3
         ON T1.CAR_TYPE IN ('세단', 'SUV')
            AND T1.CAR_TYPE = T3.CAR_TYPE
            AND T3.DURATION_TYPE = '30일 이상'
            AND FLOOR(T1.DAILY_FEE * (100 - T3.DISCOUNT_RATE) / 100) * 30 BETWEEN 500000 AND 1999999
 WHERE NOT EXISTS (
       SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T2
       WHERE T1.CAR_ID = T2.CAR_ID
         AND T2.START_DATE <= '2022-11-30'
         AND T2.END_DATE   >= '2022-11-01'
       ) 
 ORDER BY 3 DESC, 2, 1 DESC;
