-- https://school.programmers.co.kr/learn/courses/30/lessons/157339
-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기.sql

SELECT C.CAR_ID,
       C.CAR_TYPE,
       CEIL(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100) * 30 AS FEE
  FROM CAR_RENTAL_COMPANY_CAR AS C
       INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
       ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
 WHERE C.CAR_TYPE IN ('세단', 'SUV') AND NOT EXISTS (
       SELECT 1
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        WHERE C.CAR_ID = H.CAR_ID AND (YEAR(H.END_DATE) = 2023 OR MONTH(H.END_DATE) IN (11, 12))
       ) AND CEIL(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100) * 30 BETWEEN 500000 AND 1999999
 ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
