SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE AS M
WHERE MONTH(DATE_OF_BIRTH)=3 AND M.GENDER = 'W' AND M.TLNO IS NOT NULL
ORDER BY M.MEMBER_ID
