-- 오프라인&온라인 판매 데이터 통합하기.sql
-- https://school.programmers.co.kr/learn/courses/30/lessons/131537

SELECT DATE_FORMAT(T.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, T.PRODUCT_ID, T.USER_ID, T.SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    UNION ALL
    SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
    FROM OFFLINE_SALE
) AS T
WHERE YEAR(T.SALES_DATE) = 2022 AND MONTH(T.SALES_DATE) = 3
ORDER BY 1, 2, 3;
